"""empty message

Revision ID: 8e6008ae683a
Revises: a1f698ad0bed
Create Date: 2022-11-30 08:34:50.236443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6008ae683a'
down_revision = 'a1f698ad0bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refeicao',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tipo_refeicao_id', sa.Integer(), nullable=False),
    sa.Column('cardapio_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['cardapio_id'], ['cardapio.id'], ),
    sa.ForeignKeyConstraint(['tipo_refeicao_id'], ['tipo_refeicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refeicao')
    # ### end Alembic commands ###
