"""empty message

Revision ID: a5769cee314c
Revises: 2b940f53f53a
Create Date: 2022-11-30 10:27:31.479227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5769cee314c'
down_revision = '2b940f53f53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil', sa.Column('siape', sa.String(length=20), nullable=False))
    op.drop_constraint('perfil_pis_key', 'perfil', type_='unique')
    op.create_unique_constraint(None, 'perfil', ['siape'])
    op.drop_column('perfil', 'pis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil', sa.Column('pis', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'perfil', type_='unique')
    op.create_unique_constraint('perfil_pis_key', 'perfil', ['pis'])
    op.drop_column('perfil', 'siape')
    # ### end Alembic commands ###
